### ISSUE TITLE
Vonalkód kapjon külön beviteli mezőt a cikkek törzsben

### ISSUE THREAD

**Issue by programozas** [programozas-kft/Zeusz-Adoraktar#2]
Eddig a Private cikkszámot használtuk erre de ez egyedi tartalmazó mező, viszont több terméknek is lehet ugyanaz a vonalkódja...

**Comment by frittmannpeter** [comment]
Ez nekünk is kell

**Comment by programozas** [comment]
114 es verzióban leprogramozva
